import {StyleSheet, Dimensions} from 'react-native';

const width = parseInt(Dimensions.get('screen').width, 10) / 360;
const height = parseInt(Dimensions.get('screen').height, 10) / 640;

export default StyleSheet.create({
  lifeCountImage: {
    width: 121 * width,
    height: 37 * height,
    marginLeft: -65 * width,
    marginTop: 15 * height,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.53,
    shadowRadius: 13.97,
  },
  lifeCountText: {
    marginLeft: 70 * width,
    marginTop: 23 * height,
    zIndex: 1,
    fontSize: 16,
    fontFamily: 'Molle-Italic',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.53,
    shadowRadius: 13.97,
    elevation: 21,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 360 * width,
    height: 65 * height,
    backgroundColor: '#C4FEF3',

    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  score: {
    flexDirection: 'row',
    backgroundColor: '#E4F9F5',
    width: 118 * width,
    height: 36 * height,
    marginTop: 14 * height,
    borderRadius: 12 * height,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.44,
    shadowRadius: 10.32,

    elevation: 16,
  },
  scoreImage: {
    width: 25 * width,
    height: 25 * width,
    marginLeft: 16 * width,
    marginTop: 7 * height,
  },
  scoreText: {
    width: 80 * width,
    height: 19 * height,
    marginTop: 8 * height,
    marginLeft: 9 * width,
    fontSize: 16,
    fontFamily: 'Molle-Italic',
    lineHeight: 25,
  },
  levelsContainer: {
    backgroundColor: '#E4F9F5',
    marginBottom: 36 * height,
  },
  levelRow: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
    width: 360 * width,
    height: 64 * height,
    backgroundColor: '#E4F9F5',
    marginVertical: 32 * height,
  },
  levelCardView: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: 64 * width,
    height: 64 * width,
    backgroundColor: '#40514E',
    borderWidth: 3 * width,
    borderRadius: 12 * width,
    borderStyle: 'solid',
    borderColor: 'red',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.53,
    shadowRadius: 13.97,
    elevation: 21,
  },
  levelText: {
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 25,
    fontFamily: 'Molle-Italic',
    color: 'white',
    width: 40 * width,
  },
  lockedImage: {
    width: 18 * width,
    height: 24 * height,
    position: 'absolute',
    start: 48,
    top: -12,
  },
  //TODO düzelt
  successImage: {
    width: 65 * width,
    height: 26 * height,
    marginTop: -15 * height,
    marginLeft: -3 * width,
    position: 'absolute',
  },
  linearGradient: {
    width: 325 * width,
    height: 403 * height,
    borderRadius: 18,
    alignItems: 'center',
  },
  optionModalSoundView: {
    width: 286 * width,
    height: 92 * height,
    flexDirection: 'row',
    marginTop: 48 * height,
    backgroundColor: '#477A70',
    justifyContent: 'space-between',
    borderRadius: 12 * height,
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.53,
    shadowRadius: 13.97,
  },
  optionModalSoundTextsView: {
    width: 112 * width,
    height: 61 * height,
    marginTop: 17,
    marginLeft: 34 * width,
    justifyContent: 'space-between',
  },
  optionModalSoundTexts: {
    fontFamily: 'OpenSans-Regular',
    color: '#FFF',
    fontSize: 24,
  },
  optionModalSwitches: {
    width: 92 * width,
    height: 92 * height,
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#A5EDDF',
    borderRadius: 12,
  },
  themesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 286 * width,
    height: 168 * height,
    marginTop: 48 * height,
  },
  selectedThemeView: {
    width: 96 * width,
    height: 125 * height,
    alignItems: 'center',
  },
  selectedThemeText: {
    width: 96 * width,
    height: 33 * height,
    fontSize: 24,
    fontFamily: 'OpenSans-Regular',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 1.6,
  },
  selectedThemeImage: {
    width: 96 * width,
    height: 96 * height,
  },
  themesView: {
    width: 167 * width,
    height: 167 * height,
    flexDirection: 'column',
  },
  themesViewRows: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 167 * width,
    height: 72 * height,
  },
  themePhotos: {
    width: 72 * width,
    height: 72 * height,
  },
});
